openapi: 3.0.0
info:
  version: 1.0.0
  title: Authentication API
  description: Documentation for authentication endpoints
paths:
  /auth/login:
    post:
      summary: Login
      description: Login with email and password to get authentication token
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          tags:
            - auth
          content:
            application/json:
              schema:
                type: object
                properties:
                  authToken:
                    type: string
                  user:
                    $ref: '#/components/schemas/UserData'
        '401':
          description: Unauthorized
  /auth/signup:
    post:
      summary: Signup
      description: Signup with email, password, first name, and last name to get authentication token
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          tags:
            - auth
          content:
            application/json:
              schema:
                type: object
                properties:
                  authToken:
                    type: string
                  user:
                    $ref: '#/components/schemas/UserData'
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
  /auth/verify:
    post:
      summary: Verify
      description: Verify authentication token
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                authToken:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserData'
        '401':
          description: Unauthorized
components:
  schemas:
    UserData:
      type: object
      properties:
        users_data_id:
          type: integer
        name_id:
          type: integer
        user_id:
          type: integer
        email:
          type: string
        snap_timestamp:
          type: string
      required:
        - users_data_id
        - name_id
        - user_id
        - email
        - snap_timestamp

  securitySchemes:
    bearerAuth:     # This can be any name you want
      type: http
      scheme: bearer
