name: Auto test 

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Display Node.js version
      run: node -v
    
    - name: Display npm version
      run: npm -v

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
